# Office出たら通知
###########################################
- id: 6ggmxgv5egl6
  alias: auto_notify_k1_office1
  trigger:
  - entity_id: device_tracker.life360_k1asa
    event: leave
    platform: zone
    zone: zone.osaki
  action:
  - data:
      value1: kが職場から離脱
    service: script.notify_line_mtg
  initial_state: true

# Office出たら通知
###########################################
- id: f2cdarb95ei4
  alias: auto_notify_k1_office2
  trigger:
  - entity_id: device_tracker.life360_k1asa
    event: leave
    platform: zone
    zone: zone.shonan
  action:
  - data:
      value1: kが職場から離脱
    service: script.notify_line_mtg
  initial_state: true

# Office出たら通知
###########################################
- id: h978qstl8p78
  alias: auto_notify_r_office
  trigger:
  - entity_id: device_tracker.life360_reina
    event: leave
    platform: zone
    zone: zone.nailr
  action:
  - data:
      message: rが職場を離脱
    service: notify.ios_k1_phone
  - data:
      value1: rが職場を離脱
    service: script.notify_line_mtg
  initial_state: true

# 地元駅着いたら通知
###########################################
- id: kchc3o43cfdu
  alias: auto_notify_k1_ikuta
  trigger:
  - entity_id: device_tracker.life360_k1asa
    event: enter
    platform: zone
    zone: zone.ikuta
  action:
  - data:
      value1: kが生田駅
    service: script.notify_line_mtg
  initial_state: true

# 地元駅着いたら通知
###########################################
- id: 0qd9wxtx0un6
  alias: auto_notify_r_ikuta
  trigger:
  - entity_id: device_tracker.life360_reina
    event: enter
    platform: zone
    zone: zone.ikuta
  action:
  - data:
      message: rが生田駅
    service: notify.ios_k1_phone
  - data:
      value1: rが生田駅
    service: script.notify_line_mtg
  initial_state: true

# 地元駅着いたら通知
###########################################
- id: 0qd9wxtx0un6
  alias: auto_notify_r_ikuta
  trigger:
  - entity_id: device_tracker.life360_reina
    event: enter
    platform: zone
    zone: zone.ikuta
  action:
  - data:
      message: rが生田駅
    service: notify.ios_k1_phone
  - data:
      value1: rが生田駅
    service: script.notify_line_mtg
  initial_state: true

# 地元駅着いたら通知
###########################################
- id: g9ekkv7i5x5n
  alias: auto_notify_r_kumagaya
  trigger:
  - entity_id: device_tracker.life360_reina
    event: enter
    platform: zone
    zone: zone.kumagaya
  action:
  - data:
      value1: rが熊谷駅
    service: script.notify_line_mtg
  initial_state: true

# 帰宅したら通知
###########################################
- id: enwbmld9uhpi
  alias: auto_notify_r_home
  trigger:
  - entity_id: device_tracker.life360_reina
    event: enter
    platform: zone
    zone: zone.home
  action:
  - data:
      message: rが生田帰宅
    service: notify.ios_k1_phone
  - data:
      value1: rが生田帰宅
    service: script.notify_line_mtg
  initial_state: true

# 帰宅したら通知
###########################################
- id: kKjOM31339au
  alias: auto_notify_r_home_r
  trigger:
  - entity_id: device_tracker.life360_reina
    event: enter
    platform: zone
    zone: zone.home_r
  action:
  - data:
      message: rが熊谷帰宅
    service: notify.ios_k1_phone
  - data:
      value1: rが熊谷帰宅
    service: script.notify_line_mtg
  initial_state: true

# 湯沸しのON/OFFを通知
###########################################
- id: spgfcdgdf26a
  alias: HotWater_autoOff
  trigger:
  - at: 06:30:00
    platform: time
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: device_tracker.life360_k1asa
      state: home
    - condition: state
      entity_id: device_tracker.life360_reina
      state: home
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.sonoff4
  - service: script.notify_line_log
    data:
      value1: 湯沸しon
  - delay: 01:00:00
  - service: switch.turn_off
    data:
      entity_id: switch.sonoff4
  - data:
      value1: 湯沸しoff
    service: script.notify_line_log
  initial_state: true

# 毎月1日に積算電気代をリセット
###########################################
- id: ebjxrmjw0fyd
  alias: Reset Value of total at 1st day per month
  trigger:
  - platform: time_pattern
    hours: '0'
    minutes: /10
    seconds: '0'
  condition:
    condition: template
    value_template: '{{now().day | int == 1}}'
  action:
  - service: mqtt.publish
    data:
      topic: cmnd/sonoffP1/EnergyReset3
      payload: '0'
  - service: mqtt.publish
    data:
      topic: cmnd/sonoffP2/EnergyReset3
      payload: '0'
#  - service: script.notify_line_log
#    data_template:
#      value1: '前月の電気代" {{ states('') }}'
  - service: script.notify_line_log
    data:
      value1: 電気代積算リセット実行済

# 各装置のping無応答時に通知
###########################################
- id: bduyv2h58clh
  alias: notify_blue_offline
  trigger:
    platform: state
    entity_id: binary_sensor.blueastray
    from: "on"
    to: "off"
  condition: []
  action:
  - data:
      value1: "Blue Offline"
    service: script.notify_line_log

- id: x1941jzarowr
  alias: notify_gold_offline
  trigger:
    platform: state
    entity_id: binary_sensor.goldastray
    from: "on"
    to: "off"
  condition: []
  action:
  - data:
      value1: "Gold Offline"
    service: script.notify_line_log

- id: rlaa3ggqm57s
  alias: notify_green_offline
  trigger:
    platform: state
    entity_id: binary_sensor.greenastray
    from: "on"
    to: "off"
  condition: []
  action:
  - data:
      value1: "Green Offline"
    service: script.notify_line_log

- id: 9iezmtue767l
  alias: notify_Mirage_offline
  trigger:
    platform: state
    entity_id: binary_sensor.mirageastray
    from: "on"
    to: "off"
  condition: []
  action:
  - data:
      value1: "Mirage Offline"
    service: script.notify_line_log

- id: hnk56cex02xh
  alias: notify_MainRT_offline
  trigger:
    platform: state
    entity_id: binary_sensor.mainrouter
    from: "on"
    to: "off"
  condition: []
  action:
  - data:
      value1: "MainRT Offline"
    service: script.notify_line_log

- id: i60noxozdlee
  alias: notify_SubRT_offline
  trigger:
    platform: state
    entity_id: binary_sensor.subrouter
    from: "on"
    to: "off"
  condition: []
  action:
  - data:
      value1: "SubRT Offline"
    service: script.notify_line_log

- id: snjbgn2i4tu7
  initial_state: true
  alias: txt_to_sendline
  trigger:
  - platform: state
    entity_id: input_text.sendline
  action:
  - service: script.notify_line_mtg
    data_template:
      value1: '{{ trigger.to_state }}'

- id: r5f8s0nf40gz
  initial_state: true
  alias: GPSlogsR
  trigger:
  - platform: state
    entity_id: device_tracker.life360_reina
  action:
  - service: ifttt.trigger
    data_template:
      event: "reinalog"
      value1: "{{ state_attr('device_tracker.life360_reina', 'latitude') }}"
      value2: "{{ state_attr('device_tracker.life360_reina', 'longitude') }}"
      value3: "{{ state_attr('device_tracker.life360_reina', 'gps_accuracy') }}"

- id: z6coo1hlfika
  initial_state: true
  alias: GPSlogsK
  trigger:
  - platform: state
    entity_id: device_tracker.life360_k1asa
  action:
  - service: ifttt.trigger
    data_template:
      event: "k1log"
      value1: "{{ state_attr('device_tracker.life360_k1asa', 'latitude') }}"
      value2: "{{ state_attr('device_tracker.life360_k1asa', 'longitude') }}"
      value3: "{{ state_attr('device_tracker.life360_k1asa', 'gps_accuracy') }}"
