- platform: ping
  host: 192.168.3.1
  count: 4
  name: 'Main-Router'
  scan_interval: 180
  
- platform: ping
  host: 192.168.3.2
  count: 4
  name: 'Blue-Astray'
  scan_interval: 180
  
- platform: ping
  host: 192.168.3.3
  count: 4
  name: 'Red-Astray'
  scan_interval: 180
  
- platform: ping
  host: 192.168.3.4
  count: 4
  name: 'Gold-Astray'
  scan_interval: 180
  
- platform: ping
  host: 192.168.3.5
  count: 4
  name: 'Green-Astray'
  scan_interval: 180
  
- platform: ping
  host: 192.168.3.6
  count: 4
  name: 'Mirage-Astray'
  scan_interval: 180
  
- platform: ping
  host: 192.168.3.210
  count: 4
  name: 'Sub-Router'
  scan_interval: 180
