######################
# (停止)Pi Camera
######################
#- platform: ffmpeg
#  input: /dev/video0

######################
# motion + motioneye を入れてそっちに動体検知を任せる
######################
- platform: mjpeg
  name: "Living Cam"
  mjpeg_url: http://192.168.3.5:8081
#  still_image_url: http://60.126.34.61:8765/picture/1/current/?_username=admin&_signature=a78c9744d485ee0b93b0b23f7687d93ab24dd9bb
  username: !secret motion_id
  password: !secret motion_pw
  authentication: basic

######################
# motion + motioneye を入れてそっちに動体検知を任せる
######################
- platform: mjpeg
  name: "Bed Cam"
  mjpeg_url: http://192.168.3.6:8081
#  still_image_url: http://60.126.34.61:8765/picture/1/current/?_username=admin&_signature=a78c9744d485ee0b93b0b23f7687d93ab24dd9bb
  username: !secret motion_id
  password: !secret motion_pw
  authentication: basic

######################
# それぞれの場所を地図で
######################
- platform: generic
  name: "k1 map"
  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.k1_phone.attributes.latitude }},{{ states.device_tracker.k1_phone.attributes.longitude }}&zoom=15&size=300x300&maptype=roadmap&markers=color:blue%7Clabel:K1%7C{{ states.device_tracker.k1_phone.attributes.latitude }},{{ states.device_tracker.k1_phone.attributes.longitude }}&key=AIzaSyAug6WpzdW65I0WcT6zYBnf4JCqjp5IX5o
  limit_refetch_to_url_change: true
- platform: generic
  name: "ay map"
  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.ay_phone.attributes.latitude }},{{ states.device_tracker.ay_phone.attributes.longitude }}&zoom=15&size=300x300&maptype=roadmap&markers=color:pink%7Clabel:Ay%7C{{ states.device_tracker.ay_phone.attributes.latitude }},{{ states.device_tracker.ay_phone.attributes.longitude }}&key=AIzaSyAug6WpzdW65I0WcT6zYBnf4JCqjp5IX5o
  limit_refetch_to_url_change: true


#- platform: mjpeg
#  name: "雨雲レーダー"
#     ⇒YahooLocation 系のAPI使って  職場と自宅の雨雲レーダー表示を目論見中

