######################
# おおもとの設定ファイル。
#  gitで公開したくない情報は !secret <key名> で隠蔽可能。
#  →https://www.home-assistant.io/docs/configuration/secrets/
######################


homeassistant:
######################
# 基本セクション
######################
  # Customization file
  customize: !include customize.yaml
  
  whitelist_external_dirs:
  
  packages: !include_dir_named packages

######################
# 認証プロバイダ
######################
#  auth_providers:
#   - type: legacy_api_password
#     api_password: !secret http_password

######################
# 管理画面設定
######################
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  base_url: !secret base_url
  ip_ban_enabled: true
  login_attempts_threshold: 10
  cors_allowed_origins:
    - https://cast.home-assistant.io
    - http://192.168.3.5:8080
    - http://192.168.3.3:8080

###########################################
# Core Components
###########################################
config:
conversation:
frontend:
logbook:
zeroconf:

system_health:
logger:
  default: warning
  logs:
    requests.packages.urllib3.connectionpool: critical
updater:
  include_used_components: true


###########################################
# Simple Components
###########################################
cloud:
ffmpeg:
map:
ios:
sun:
wake_on_lan:
person: 

homekit:
  name: HA_Bridge
  filter:
    exclude_domains:
    - scriptmh
    exclude_entities:
    - sensor.yr_24hr_temperature
    - sensor.yr_now_temperature
    - sensor.yr_now_humidity
    - sensor.yr_24hr_humidity
    - sensor.dark_sky_temperature
    - sensor.owm_temperature

hacs:
  token: !secret github_token

discovery:
  #enable:
  #  - homekit
lock:
  - platform: sesame
    api_key: !secret sesame_key

tts:
  - platform: google_translate
    service_name: google_say
    language: 'ja'
    base_url: https://192.168.3.5:8123


#mqtt:
#  broker: !secret CLOUDMQTT_SERVER
#  port: !secret CLOUDMQTT_PORT
#  username: !secret CLOUDMQTT_USER
#  password: !secret CLOUDMQTT_PASSWORD

###########################################
# Includes
#  include で他ファイルへ飛ばせる。
#  include_dir_merge_named でフォルダ指定してすべてマージして読み込ませられる。
###########################################
automation: !include automations.yaml
camera: !include camera.yaml
group: !include_dir_merge_named groups_views
history: !include history.yaml
media_player: !include media_player.yaml
notify: !include notify.yaml
script: !include scripts.yaml
history_graph: !include history_graph.yaml
rest_command: !include rest_command.yaml
binary_sensor: !include binary_sensor.yaml

###########################################
# Third Party Platforms
###########################################
ifttt:
  key: !secret ifttt_key

device_tracker:

#life360:
#  accounts:
#    - username: !secret life360_username
#      password: !secret life360_password
#  circles:
#    include: [Family]

###########################################
# 未整理
###########################################


sensor:
    ###########################################
    # Xboxセンサー
    ###########################################
    - platform: xbox_live
      api_key: !secret xboxapi
      xuid:
        - 2797995304216926

    ###########################################
    # PiのGPIOにつないだI2C接続のbme280センサー
    ###########################################
    - platform: bme280
      name: Ambient
#      operation_mode: 2  # forced mode
#      time_standby: 5
#      oversampling_temperature: 4
#      oversampling_pressure: 4
#      oversampling_humidity: 4
#      delta_temperature: -0.5
      monitored_conditions:
        - temperature
        - humidity
        - pressure
#      scan_interval: 180



    ###########################################
    # nature Remoから室温と湿度と照度センサー読み出し
    ###########################################
    - platform: rest
      resource: https://api.nature.global/1/devices/
      name: nremo_0_hu
      device_class: humidity
      unit_of_measurement: '%'
      value_template: '{{value_json[0].newest_events.hu.val}}'
      headers:
        Authorization: !secret nature_key
      scan_interval: 120
      force_update: true

    - platform: rest
      resource: https://api.nature.global/1/devices/
      name: nremo_0_il
      device_class: illuminance
      value_template: '{{value_json[0].newest_events.il.val}}'
      headers:
        Authorization: !secret nature_key
      scan_interval: 120
      force_update: true

    - platform: rest
      resource: https://api.nature.global/1/devices/
      name: nremo_0_te
      value_template: '{{value_json[0].newest_events.te.val}}'
      unit_of_measurement: "°C"
      headers:
        Authorization: !secret nature_key
      device_class: temperature
      scan_interval: 120
      force_update: true

    - platform: rest
      resource: https://api.nature.global/1/devices/
      name: nremo_1_hu
      device_class: humidity
      unit_of_measurement: '%'
      value_template: '{{value_json[1].newest_events.hu.val}}'
      headers:
        Authorization: !secret nature_key
      scan_interval: 120
      force_update: true

    - platform: rest
      resource: https://api.nature.global/1/devices/
      name: nremo_1_il
      device_class: illuminance
      value_template: '{{value_json[1].newest_events.il.val}}'
      headers:
        Authorization: !secret nature_key
      scan_interval: 120
      force_update: true

    - platform: rest
      resource: https://api.nature.global/1/devices/
      name: nremo_1_te
      device_class: temperature
      unit_of_measurement: "°C"
      value_template: '{{value_json[1].newest_events.te.val}}'
      headers:
        Authorization: !secret nature_key
      scan_interval: 120
      force_update: true

    ###########################################
    # Sonoff Pow から値読み出し
    ###########################################
    - platform: template
      sensors:
        p2_price:
          friendly_name: '電気料金概算'
          unit_of_measurement: '円'
          icon_template: mdi:currency-jpy
          value_template: >-
            {% if is_state('sensor.sonoffp2_energy_total','unknown') %}
            0
            {% else %}
            {{ (states('sensor.sonoffp2_energy_total')|float * 23.408 ) | round(2) }}
            {% endif %}
        p1_price:
          friendly_name: '電気料金概算'
          unit_of_measurement: '円'
          icon_template: mdi:currency-jpy
          value_template: >-
            {% if is_state('sensor.sonoffp1_energy_total','unknown') %}
            0
            {% else %}
            {{ (states('sensor.sonoffp1_energy_total')|float * 23.408 ) | round(2) }}
            {% endif %}

    ###########################################
    # Pi Zero から値読み出し
    ###########################################
    - platform: mqtt
      name: 'bed_bme280_temp'
      state_topic: 'tele/bed_bme280/sensor'
      value_template: '{{ value_json["temperature"] }}'
      unit_of_measurement: '°C'
      device_class: temperature
#    - platform: mqtt
#      name: 'bed_bme280_pressure'
#      state_topic: 'tele/bed_bme280/sensor'
#      value_template: '{{ value_json["pressure"] }}'
#      unit_of_measurement: 'mb'
#      icon: mdi:nature
#      friendly_name: 'bed280 気圧'

light:
    ###########################################
    # Nanoleaf Aurora操作
    ###########################################
  - platform: nanoleaf
    name: 'オーロラ'
    host: 192.168.3.19
    token: !secret aurora_token
    ###########################################
    # nRemoのScript呼び出し
    ###########################################
  - platform: template
    lights:
      living:
        friendly_name: 'リビング照明'
        turn_on:
          service: script.light_living_on
        turn_off:
          service: script.light_living_off
      dining:
        friendly_name: 'ダイニング照明'
        turn_on:
          service: script.light_dining_on
        turn_off:
          service: script.light_dining_off
      bed:
        friendly_name: 'ベッド照明'
        turn_on:
          service: script.light_bed_on
        turn_off:
          service: script.light_bed_off

    

switch:
  ###########################################
  # Windowsマシンのon/off
  #  wake on lanで起動して、pingで生死確認して、RPCshutdownで終了
  ###########################################
  - platform: wake_on_lan
    name: 'Red-Astray'
    host: 192.168.3.3
    mac_address: '40-8D-5C-53-16-3A'
    turn_off: 
      service: script.addon_rpcshutdown_redastray
      
  ###########################################
  # エアコンのon/offスイッチ。script経由でrest_command操作
  ###########################################
  - platform: template
    switches:
      aircon_bed:
        value_template: "{% if states('sensor.p2_power') | float > 3 %}true{%else%}false{% endif %}"
        turn_on:
          service: script.aircon_bed
        turn_off:
          service: script.aircon_bed_off
  - platform: template
    switches:
      aircon_living:
        value_template: "{% if states('sensor.p1_power') | float > 3 %}true{%else%}false{% endif %}"
        turn_on:
          service: script.aircon_living
        turn_off:
          service: script.aircon_living_off

input_text:
  ###########################################
  # MQTT経由のSonoff Basic1
  ###########################################
  sendline:
    name: send to LINE
    min: 1
    initial: input text
    