###############################################################################
#   @author         :   k1asa
#   @date           :   08/30/2019
#   @package        :   Home Assistant
###############################################################################
homeassistant:

###############################################################################
#  Script
###############################################################################
script:
  stop_hass:
    sequence:
      - service: shell_command.stop_hass
  update_hass:
    sequence:
      - service: shell_command.update_hass
  restart_hass:
    sequence:
      - service: shell_command.restart_hass

shell_command:
  stop_hass: >-
    hassctl stop

  restart_hass: >-
    hassctl restart

  update_hass: >-
    hassctl update-hass && hassctl config && hassctl restart


###############################################################################
#  Etc
###############################################################################

# Speedtest.netで速度計測
######################################################
speedtestdotnet:
  scan_interval:
    hours: 1
  monitored_conditions:
    - ping
    - download
    - upload
  server_id: 6087

###############################################################################
#  Sensor
###############################################################################

sensor:

    # rpi_起動時間
    ###########################################
  - platform: uptime
    name: Home Assistant Up Time
    unit_of_measurement: hours

    # rpi_外部IP
    ###########################################
  - platform: rest
    resource: http://icanhazip.com
    name: external_ip
    value_template: '{{ value }}'
    scan_interval: 86400

    # rpi_各ステータス
    ###########################################
  - platform: systemmonitor
    resources:
      - type: disk_free
        arg: /
      - type: memory_free
      - type: processor_use
      - type: ipv4_address
        arg: wlan0
      - type: last_boot
      - type: disk_use_percent
        arg: /

    # rpi_CPU温度
    ###########################################
  - platform: command_line
    name: CPU温度
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) }}'

    # rpi_電流値センサー
    ###########################################
  - platform: rpi_power
    text_state: true

    # 外部IP
    ###########################################
  - platform: dnsip

    # hass最新ver
    ###########################################
  - platform: rest
    resource: https://pypi.python.org/pypi/homeassistant/json
    name: HA Current Version
    value_template: '{{ value_json.info.version }}'

    # hass現ver
    ###########################################
  - platform: version
    name: HA Installed Version

    # WIFI強度
    ###########################################
  - platform: command_line
    name: Wifi Signal
    command: 'iwconfig wlan0 |grep Signal|cut -d"=" -f3|cut -d" " -f1'
    unit_of_measurement: " dBm"
    value_template: '{{ value | round(1) }}'


###############################################################################
#  Automation
###############################################################################

automation:

# Notify me when I get a new public IP from my ISP
######################################################
  - alias: Notify Of New External IP
    initial_state: true
    trigger:
      platform: state
      entity_id: sensor.myip
    condition:
      - condition: template
        value_template: "{% if trigger.from_state and trigger.to_state %} true {% else %} false {% endif %}"
      - condition: template
        value_template: "{% if trigger.from_state.state == 'unknown' %} false {% else %} true {% endif %}"
      - condition: template
        value_template: "{% if trigger.to_state.state == 'unknown' %} false {% else %} true {% endif %}"
      - condition: template
        value_template: "{{ trigger.from_state.state != trigger.to_state.state }}"
    action:
      - service: script.notify_line_log
        data_template:
          message: "Your External IP changed from {{ trigger.from_state.state }} to {{ trigger.to_state.state }}"

# Notify me when I get a new public IP from my ISP
######################################################
  - alias: Update Available Notification
    initial_state: true
    trigger:
      platform: state
      entity_id: updater.updater
    action:
      - service: script.notify_line_log
        data: {"message":"New HASS update is available. Please update!"}

# HomeAssistant起動完了時に通知
###########################################
  - alias: HA is online
    id: 'a57uqgqieii7'
    initial_state: true
    trigger:
      platform: homeassistant
      event: start
    action:
    - service: script.notify_line_log
      data: 
        value1: "HA is start"

# HomeAssistantの起動時にiOSへ位置情報uploadを指示
###########################################
  - alias: Update IOS location on HA start
    initial_state: true
    id: 'dhevxq3hyloi'
    trigger:
      platform: homeassistant
      event: start
    action:
#    - service: notify.ios_r_phone
#      data:
#        message: "request_location_update"
    - delay: 00:00:01
    - service: notify.ios_k1_phone
      data:
        message: "request_location_update"
    - delay: 00:00:20
#  - service: notify.ios_r_phone
#    data:
#      message: "request_location_update"
    - delay: 00:00:01
    - service: notify.ios_k1_phone
      data:
        message: "request_location_update"

# HomeAssistant起動時にsonoff-tasmotaへ指示
###########################################
  - alias: Power state on HA start-up
    id: 'tj9p3oabuk63'
    trigger:
      platform: homeassistant
      event: start
    action:
    - service: mqtt.publish
      data:
        topic: cmnd/sonoffs/SetOption19
        payload: '1'
    - service: mqtt.publish
      data:
        topic: cmnd/sonoffs/state
        payload: ''