###############################################################################
#   @author         :   k1asa
#   @date           :   08/30/2019
#   @package        :   Home Assistant
###############################################################################
homeassistant:

###############################################################################
#  Script
###############################################################################
script:


###############################################################################
#  Etc
###############################################################################
weather:
  - platform: openweathermap
    api_key: !secret openweathermap_key
  - platform: darksky
    api_key: !secret darksky_key
    mode: daily
#  - platform: yweather

###############################################################################
#  Sensor
###############################################################################

sensor:

    # 日の出、日の入り算出センサー
    ###########################################
    - platform: template
      sensors:
        day_night:
          friendly_name: 'Day/Night'
          value_template: '{% if is_state("sun.sun", "above_horizon") %}Day{% else %}Night{% endif %}'
          icon_template: '{% if is_state("sun.sun", "above_horizon") %}mdi:weather-sunny{% else %}mdi:weather-night{% endif %}'

    # 月の満ち欠けセンサー(英語)
    ###########################################
    - platform: moon

    # 月の満ち欠けセンサー(日本語)
    ###########################################
    - platform: template
      sensors:
        moon_template:
          friendly_name: 'moon'
          value_template: >-
            {% if is_state('sensor.moon','new_moon') %}
            新月
            {% elif is_state('sensoraa.moon','waxing_crescent') %}
            三日月
            {% elif is_state('sensor.moon','first_quarter') %}
            上弦の月
            {% elif is_state('sensor.moon','waxing_gibbous') %}
            十日夜の月
            {% elif is_state('sensor.moon','full_moon') %}
            満月
            {% elif is_state('sensor.moon','waning_gibbous') %}
            寝待月
            {% elif is_state('sensor.moon','last_quarter') %}
            下弦の月
            {% elif is_state('sensor.moon','waning_crescent') %}
            有明月
            {% else %}
            unknown
            {% endif %}

    # 「今は夏ですｷﾘｯ」って教えてくれるセンサー
    ###########################################
    - platform: season
      type: astronomical

    # 「今は夏ですｷﾘｯ」って教えてくれるしアイコンも変わるセンサー
    ###########################################
    - platform: template
      sensors:
        season_template:
          friendly_name: 'Season'
          value_template: >-
            {%- if is_state("sensor.season", "spring") %}
              Spring
            {%- elif is_state("sensor.season", "summer") %}
              Summer
            {%- elif is_state("sensor.season", "autumn") %}
              Autumn
            {%- elif is_state("sensor.season", "winter") %}
              Winter
            {% else %}
              None
            {% endif %}
          icon_template: >-
            {%- if is_state("sensor.season_template", "Spring") %}
              mdi:weather-sunset
            {%- elif is_state("sensor.season_template", "Summer") %}
              mdi:weather-sunny
            {%- elif is_state("sensor.season_template", "Autumn") %}
              mdi:leaf
            {%- elif is_state("sensor.season_template", "Winter") %}
              mdi:weather-snowy
            {% else %}
              mdi:weather-snowy-rainy
            {% endif %}

    # Darksky
    ###########################################
    - platform: darksky
      api_key: !secret darksky_key
      language: ja
      monitored_conditions:
      - summary
      - temperature
      - wind_speed
      - humidity
      - hourly_summary
      - daily_summary
      - temperature_high
      - temperature_low
      - uv_index

    # OpenWeatherMap
    ###########################################
#    - platform: openweathermap
#      api_key: !secret openweathermap_key
#      language: ja
#      monitored_conditions:
#      - weather
#      - temperature
#      - wind_speed
#      - humidity
#      - pressure
#      - rain
#      - snow

    # Yahoo天気
    ###########################################
#    - platform: yweather
#      monitored_conditions:
#      - weather_current
#      - temp_min
#      - temp_max
#      - wind_speed
#      - pressure
#      - humidity
#      - temperature


###############################################################################
#  Binary Sensor
###############################################################################

binary_sensor:
  - platform: workday
    country: JP

###############################################################################
#  Automation
###############################################################################

automation:
